# █████████████████████████████████████▀██████████████████████████████████████████████████████████
# █▄─▄▄─█▄─▄█─▄▄▄▄█─█─█▄─▄█▄─▀█▄─▄█─▄▄▄▄███▄─▄▄─█▄─▀─▄█▄─▄▄─██▀▄─██▄─▀█▄─▄█─▄▄▄▄█▄─▄█─▄▄─█▄─▀█▄─▄█
# ██─▄████─██▄▄▄▄─█─▄─██─███─█▄▀─██─██▄─████─▄█▀██▀─▀███─▄▄▄██─▀─███─█▄▀─██▄▄▄▄─██─██─██─██─█▄▀─██
# ▀▄▄▄▀▀▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▄▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▀▀▄▄▄▄▄▀▄▄█▄▄▀▄▄▄▀▀▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▀▄▄▄▀▀▄▄▀

items:
  DIAMOND:
    chance: 0.05
    command: "give %player% diamond 1"
  IRON_INGOT:
    chance: 0.2
  GOLD_NUGGET:
    chance: 0.1
    command: "say %player% got a gold nugget!"
