name: FishingExpansion
version: 1.0
main: me.craftystudios.fishing.Main
commands:
  fishingexpansion:
    description: FishingExpansion command
    usage: /fishingexpansion
    aliases: [fe]
    permission: fishingexpansion.command
    permission-message: You don't have permission to use this command!
    default: true
    tab-completer: me.craftystudios.fishing.Commands.fishingexpansion
    executor: me.craftystudios.fishing.Commands.fishingexpansion

