name: FishingExpansion
version: 1.0
api-version: 1.19
main: me.craftystudios.fishing.Main
commands:
  fishing-expansion:
    description: FishingExpansion command
    usage: /fishing-expansion
    aliases: [fe]
    permission: fishingexpansion.command
    permission-message: You don't have permission to use this command!
    default: true
    tab-completer: me.craftystudios.fishing.Commands.fishingexpansion
    executor: me.craftystudios.fishing.Commands.fishingexpansion

